version: '3.8'

services:


  test-service-postgres:
    image: postgres:14
    container_name: test-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

