version: '3'
services:

  consul-1:
    image: gliderlabs/consul
    container_name: consul-1
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8400:8400"
      - "8500:8500"
      - "3.3.3.2:53:8600/udp"
    env_file: .env
    volumes:
      - ./start-consul-agent.sh:/start-consul-agent.sh
    entrypoint: /start-consul-agent.sh
