version: '3.7'

services:

  test1:
    container_name: test1
    # restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/back.Dockerfile
      args:
        PROJECT_ID: ${PROJECT_ID}
        ACCESS_TOKEN: ${ACCESS_TOKEN}
    env_file:
      - ../.env
